public enum TalepDurumu {
    ACIK,
    LIDER_ATAMA_BEKLIYOR,
    EKIP_LIDERINDE,
    TEKNIK_CALISANLARA_ATANDI,
    ISLEMDE,
    ATAMA_BEKLIYOR,
    MUSTERI_YANITI_BEKLIYOR,
    CALISANLAR_ISI_TAMAMLADI,
    EKIP_LIDERI_ONAY_BEKLIYOR,
    COZULDU_ONAY_BEKLIYOR,
    KAPANDI,
    ISLEMDE_GERI_DONDU
}